version: '3'

services:
  server:
    container_name: raphael_node
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3200:3200'
  db:
    image: 'mongo'
    container_name: raphael_mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      